### ISSUE TITLE
Set up Bingether Endpoints

### ISSUE THREAD

**Issue by SavenR** [SavenR/Bingether#137]
Sub-issues:
- [ ] Create Bingether serializer #138
- [ ] All active Bingethers endpoint #134
- [ ] All active Bingethers created by a user endpoint #135
- [ ] Bingether serializer endpoint #136
